name: Docker Version Check

on: [push]

jobs:
  check-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Docker Version
      run: docker -v
    
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker build -t "flaskserver" .

  connect-docker-hub:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Tag Image
        run: docker tag flashserver nathandoly/ndflaskserver
      - name: Push Image to Docker Hub
        run: docker push nathandoly/ndflaskserver
    
    