name: Docker Version Check

on: [push]

jobs:
  check-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Docker Version
      run: docker -v
    
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker build -t "flaskserver" .
