name: Docker Workflow

on: [push]

jobs:
  check-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Docker Version
      run: docker -v
    
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build -t flaskserver .

  connect-docker-hub:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

  checkimage:
    needs: connect-docker-hub
    runs-on: ubuntu-latest

    steps:
    - name: Check Image
      run: docker images

  push-image:
    needs: checkimage
    runs-on: ubuntu-latest

    steps:
    - name: Tag Image
      run: docker tag flaskserver ${{ secrets.DOCKER_HUB_USERNAME }}/ndflaskserver
    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ndflaskserver
